name: Test the Star Wars Name Action

on:
  workflow_dispatch:

jobs:
  generate-star-wars-name:
    name: Generate Star Wars Name
    runs-on: ubuntu-latest

    steps:
    - name: Generate Star Wars Name for Robert England
      id: roberts-star-wars-name
      uses: msfred/star-wars-name-action@log
      with:
        FirstName: Robert
        LastName: England
        BirthTown: London
        MaidenName: Stewart

    - name: Generate Star Wars Name for Fred Gohsman
      id: freds-star-wars-name
      uses: msfred/star-wars-name-action@log
      with:
        FirstName: Fred
        LastName: Gohsman
        BirthTown: Saginaw
        MaidenName: Reynolds

    - name: Use output from Action later
      run: |
        echo 'Generated name for Robert England: ${{ steps.roberts-star-wars-name.outputs.StarWarsName }}'
        echo 'Generated name for Fred Gohsman: ${{ steps.freds-star-wars-name.outputs.StarWarsName }}'