name: Test the Star Wars Name Action

on:
  workflow_dispatch:
    inputs:
      FirstName:
        description: 'Your first name'
        type: string
        default: 'William'
        required: true
      LastName:
        description: 'Your last name'
        type: string
        default: 'Gates'
        required: true
      BirthTown:
        description: 'The town where you were born'
        type: string
        default: 'Seattle'
        required: true
      MaidenName:
        description: 'Your mother''s maiden name.  ie, last name before marriage'
        type: string
        default: 'Maxwell'
        required: true

jobs:
  generate-star-wars-name:
    name: 'Generate Star Wars Name'
    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Generate Star Wars Name for Robert England'
      id: roberts-star-wars-name
      uses: msfred/star-wars-name-action@v1
      with:
        FirstName: ${{ inputs.FirstName }}
        LastName: ${{ inputs.LastName }}
        BirthTown: ${{ inputs.BirthTown }}
        MaidenName: ${{ inputs.MaidenName }}

    - name: 'Use output from Action later'
      run: |
        echo 'Generated name for Robert England: ${{ steps.roberts-star-wars-name.outputs.StarWarsName }}'
        echo 'Generated name for Fred Gohsman: ${{ steps.freds-star-wars-name.outputs.StarWarsName }}'
  
